services:
  identety_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=identety
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
