name: Deployment to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Continuous Deployment to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            cd ./apps/identety
            git clean -f
            sudo chown -R $USER:$USER docker-volumes/
            git pull origin main --ff-only
            docker compose down
            docker compose up -d --build
